@baseUrl = http://localhost:5001


### GET request to example server
GET {{baseUrl}}
Content-Type: application/json
###


### GET request to example server
GET {{baseUrl}}/characters


###GET na artefakty
GET {{baseUrl}}/artefacts

